# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  build:
    # machine: true
    resource_class: jluiiizz/hme
    working_directory: ~/app
    docker:
      - image: cimg/base
    steps:
      - checkout
      # - setup_remote_docker
      - setup_remote_docker:
          version: 20.10.14
      - run: 
          name: Docker Build
          command: | 
            docker build -t circleci-test-api:latest .
      - run: 
          name: Show Docker Images
          command: | 
            docker images

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              only:
                master